PKG-2007: rebuild for new boost
AnacondaRecipes/pyarrow-feedstock pull request #15
Opened 2023-07-31 15:03 UTC by rafaelmartins

2023-07-31 15:04 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:13: invalid_url: https://dist.apache.org/repos/dist/release/arrow/arrow-11.0.0/apache-arrow-11.0.0.tar.gz : Not reachable: 404
Errors were found

</details>

2023-07-31 15:05 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:13: invalid_url: https://dist.apache.org/repos/dist/release/arrow/arrow-11.0.0/apache-arrow-11.0.0.tar.gz : Not reachable: 404
Errors were found

</details>

2023-08-01 13:06 UTC, JeanChristopheMorinPerso approved these changes

2023-08-01 13:06 UTC, JeanChristopheMorinPerso requested changes
I thihnk you will need to bump the build number

2023-08-01 13:10 UTC, rafaelmartins commented
> I thihnk you will need to bump the build number

indeed. thanks :)

2023-08-01 13:10 UTC, JeanChristopheMorinPerso approved these changes

2023-08-01 13:23 UTC, M-Waszkiewicz-Anaconda approved these changes
LGTM

2023-08-29 01:31 UTC, merged